server.port=8082
spring.application.name=junior-spring-interview

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/junior_db
spring.datasource.username=junior
spring.datasource.password=secret
spring.datasource.hikari.connection-init-sql=SET TIMEZONE='UTC'
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.indent_output=true
