proxy_cache_path D:/Junior/nginx/cache
                 levels=1:2
                 keys_zone=product_api_cache:20m
                 max_size=500m
                 inactive=10m
                 use_temp_path=off;

upstream junior_api {
    server 127.0.0.1:8082;
    keepalive 32;
}

server {
    listen 80;
    server_name localhost;

    location = /__nginx_test {
        add_header X-Debug-Server junior-proxy always;
        return 200 "junior nginx config is active";
    }

    location /api/products {
        proxy_pass http://junior_api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";

        proxy_cache product_api_cache;
        proxy_cache_key "$scheme$request_method$host$request_uri";
        proxy_cache_methods GET HEAD;

        proxy_cache_valid 200 200s;
        proxy_cache_valid 404 5s;

        proxy_cache_lock on;
        proxy_cache_revalidate on;
        proxy_cache_background_update on;

        proxy_cache_bypass $http_authorization $arg_nocache;
        proxy_no_cache $http_authorization;

        add_header X-Debug-Server junior-proxy always;
        add_header X-Cache-Status $upstream_cache_status always;
    }
}
